// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhqDXUac8t7-LHVucoiXVLfoJuLAss_M',
    appId: '1:748797522693:web:79e9e322ddfc4578d8bd6c',
    messagingSenderId: '748797522693',
    projectId: 'localservice-2352e',
    authDomain: 'localservice-2352e.firebaseapp.com',
    storageBucket: 'localservice-2352e.firebasestorage.app',
    measurementId: 'G-C54JKVLBDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0jG9RFtjsEP4y7Dy2a_p6KFCETc9JeU',
    appId: '1:748797522693:android:cb075983b27a3946d8bd6c',
    messagingSenderId: '748797522693',
    projectId: 'localservice-2352e',
    storageBucket: 'localservice-2352e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49rrtC364lsQVbxXpDkqaYIhSgyFXMdQ',
    appId: '1:748797522693:ios:4c203c2e738b8accd8bd6c',
    messagingSenderId: '748797522693',
    projectId: 'localservice-2352e',
    storageBucket: 'localservice-2352e.firebasestorage.app',
    iosBundleId: 'com.localservice.localServiceApp',
  );
}
